name: finwise
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev
publish_to: 'none'

# Version and build number for your application
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0 
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.5.1
  flutter_markdown: ^0.6.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# Uncomment and add your asset paths below
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg

# Uncomment and add your custom fonts below
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
